# Generated by Django 3.1.6 on 2021-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_address', models.CharField(max_length=200)),
                ('org_city', models.CharField(max_length=50)),
                ('org_inn', models.PositiveBigIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('uid', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
