# Generated by Django 3.1.6 on 2021-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания записи')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='дата обновления информации')),
                ('serial_no', models.TextField(blank=True, verbose_name='серийный номер')),
                ('type_id', models.IntegerField(blank=True, verbose_name='id типа оборудования')),
                ('model_id', models.IntegerField(blank=True, verbose_name='id модели оборудования')),
                ('manufacturer_id', models.IntegerField(blank=True, verbose_name='id производителя')),
                ('organization_id', models.IntegerField(blank=True, verbose_name='id организации, которой принадлежит оборудование')),
                ('uid', models.IntegerField(verbose_name='id пользователя создавшего или изменившего запись')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
