# Generated by Django 3.1.6 on 2021-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='uid',
            field=models.IntegerField(blank=True, default=0, verbose_name='id пользователя создавшего или изменившего запись'),
        ),
    ]
