# Generated by Django 3.1.6 on 2021-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210304_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='серийный номер'),
        ),
    ]
